# Form implementation generated from reading ui file '.\docx2pdfgui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 341)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.fileDialogBtn = QtWidgets.QToolButton(parent=self.centralwidget)
        self.fileDialogBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.fileDialogBtn.setObjectName("fileDialogBtn")
        self.gridLayout.addWidget(self.fileDialogBtn, 2, 1, 1, 1)
        self.startBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startBtn.setMinimumSize(QtCore.QSize(150, 35))
        self.startBtn.setObjectName("startBtn")
        self.gridLayout.addWidget(self.startBtn, 3, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pathLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pathLine.setReadOnly(True)
        self.pathLine.setObjectName("pathLine")
        self.gridLayout.addWidget(self.pathLine, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Docx2PDF Book Fold Printing"))
        self.fileDialogBtn.setText(_translate("MainWindow", "..."))
        self.startBtn.setText(_translate("MainWindow", "Старт"))
        self.label.setText(_translate("MainWindow", "Выберите папку, содержащую файлы для печати (.docx, .doc):"))
